### ISSUE TITLE
Issue with VSeeFace

### ISSUE THREAD

**Issue by DapperOfficialDiamond** [kitsune-ONE-team/KITSUNETSUKI-Asset-Tools#1]
Hey um when I try to import my model into vseeface I get this error ![IMG_20211016_095202](https://user-images.githubusercontent.com/92644757/137596600-949fe789-9480-4e68-9530-d9ec836bcb3b.jpg)

**Comment by Yonnji** [comment]
Can you also post VSeeFace log file - Player.log? It should be in Emiliana_vt folder, somewhere in your %APPDATA%

**Comment by DapperOfficialDiamond** [comment]
--file removed--

**Comment by Yonnji** [comment]
It looks like you missing some bones. Can you send me VRM file?

**Comment by DapperOfficialDiamond** [comment]
it says it doesnt support that file type

**Comment by Yonnji** [comment]
You may upload it to dropbox or google drive and post a link.

**Comment by DapperOfficialDiamond** [comment]
Sorry for the hold up: --link removed--

**Comment by Yonnji** [comment]
Thanks, I got the files and removed links. Found a bug, upper leg bones are not detected. I will fix it in the next version.

**Comment by DapperOfficialDiamond** [comment]
k thanks, also this will be my final question, do you when the next version will be released? no pressure to answer nor to work on it, just wonderin'.

**Comment by Yonnji** [comment]
tomorrow, I think...

**Comment by DapperOfficialDiamond** [comment]
Alright, thank you.

**Comment by Yonnji** [comment]
It should be fixed for now in https://github.com/kitsune-ONE-team/KITSUNETSUKI-Asset-Tools/releases/tag/0.6.5
