### ISSUE TITLE
Error instaling addon on blender

### ISSUE THREAD

**Issue by krulld** [kitsune-ONE-team/KITSUNETSUKI-Asset-Tools#3]
Hi! when activating the addon on my blender i get this error.

![error addon](https://user-images.githubusercontent.com/95772364/145262205-15a918d8-c1b5-4f33-9ccd-24f09a46cea3.png)

I have no idea on how to read those errors, any idea what might made it pop / how to fix it?

**Comment by HappyOcean** [comment]
I had same error in blender 2.82 but no error in blender 2.93

**Comment by krulld** [comment]
It actually help me to active the addon to use the 2.93 version, but as i export to VRM i got another error

![image](https://user-images.githubusercontent.com/95772364/149236415-f6af677c-56b4-4b54-a7bf-6d7f756d68a8.png)

**Comment by Yonnji** [comment]
> It actually help me to active the addon to use the 2.93 version, but as i export to VRM i got another error

Solution - https://github.com/kitsune-ONE-team/KITSUNETSUKI-Asset-Tools/issues/2#issuecomment-1155210239

**Comment by Yonnji** [comment]
> I have no idea on how to read those errors, any idea what might made it pop / how to fix it?

It's a bug, which appears on older unsupported version of Blender (<2.92). I'll fix it in the next release. But it's not important, because the addon still can't be activated on older version of Blender.
