### ISSUE TITLE
code for vtuber SW prototype

### ISSUE THREAD

**Issue by wetoo-cando** [kitsune-ONE-team/KITSUNETSUKI-Asset-Tools#6]
Not sure if this is the right place for this, but I am wondering if you have open-sourced the code for this video somewhere: https://www.youtube.com/watch?v=ijsI7J5Zx1o

Would help immensely, thanks!

**Comment by Yonnji** [comment]
This software is available here - https://kitsune-one.itch.io/vtuber-webcam
But it's not open source.
