### ISSUE TITLE
File exported into VSeeFace cannot be loaded.

### ISSUE THREAD

**Issue by MothAngel** [kitsune-ONE-team/KITSUNETSUKI-Asset-Tools#8]
I exported a .vrm file using this addon, but VSeeFace doesn't recognize it.

"Loading VRM Avatar [(Filepath)] failed. One or more errors occurred.
If this is a VSFAvatar file, make sure it was exported from Unity 2019.4.31f1 and was exported to VRM format and reimported before being exported to VSFAvatar format."

Unity was being a pain trying to get shape keys working, so I thought this addon would cut out the middle-man and make my life easier. Please let me know ASAP if you know what happened, I followed every instruction.

**Comment by Yonnji** [comment]
Can you show the VSeeFace log file? It should be somewhere in "AppData" and called "Player.log".

**Comment by MothAngel** [comment]
Took me a while to find, but here it is:

> Loading VRM avatar failed. System.AggregateException: One or more errors occurred. ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
> Parameter name: index
>   at System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) [0x00029] in <eae584ce26bc40229c1b1aa476bfa589>:0 
>   at System.ThrowHelper.ThrowArgumentOutOfRangeException () [0x00000] in <eae584ce26bc40229c1b1aa476bfa589>:0 
>   at UniGLTF.GltfTextureImporter.CreateSRGB (UniGLTF.GltfData data, System.Int32 textureIndex, UnityEngine.Vector2 offset, UnityEngine.Vector2 scale) [0x000bd] in <367435997204480e822e328654283eab>:0 
>   at VRM.VRMImporterContext+<ReadMetaAsync>d__16.MoveNext () [0x00105] in <8b7ff894d8234a4c8faa747683d9cfa1>:0 
>    --- End of inner exception stack trace ---
>   at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00011] in <eae584ce26bc40229c1b1aa476bfa589>:0 
>   at System.Threading.Tasks.Task.Wait (System.Int32 millisecondsTimeout, System.Threading.CancellationToken cancellationToken) [0x00043] in <eae584ce26bc40229c1b1aa476bfa589>:0 
>   at System.Threading.Tasks.Task.Wait () [0x00000] in <eae584ce26bc40229c1b1aa476bfa589>:0 
>   at VRM.VRMImporterContextExtensions.ReadMeta (VRM.VRMImporterContext context, System.Boolean createThumbnail) [0x0000c] in <8b7ff894d8234a4c8faa747683d9cfa1>:0 
>   at AvatarSelect.Start () [0x000ad] in <0cd5dcad694042708f0827cf6323a0e6>:0 
> ---> (Inner Exception #0) System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
> Parameter name: index
>   at System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) [0x00029] in <eae584ce26bc40229c1b1aa476bfa589>:0 
>   at System.ThrowHelper.ThrowArgumentOutOfRangeException () [0x00000] in <eae584ce26bc40229c1b1aa476bfa589>:0 
>   at UniGLTF.GltfTextureImporter.CreateSRGB (UniGLTF.GltfData data, System.Int32 textureIndex, UnityEngine.Vector2 offset, UnityEngine.Vector2 scale) [0x000bd] in <367435997204480e822e328654283eab>:0 
>   at VRM.VRMImporterContext+<ReadMetaAsync>d__16.MoveNext () [0x00105] in <8b7ff894d8234a4c8faa747683d9cfa1>:0 <---
> 
> 
> If this is a VSFAvatar file, make sure it was exported from Unity 2019.4.31f1 and was exported to VRM format and reimported before being exported to VSFAvatar format. 
> (Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

**Comment by Yonnji** [comment]
Looks like textures was not exported or there is something wrong with them. Did you created materials with Principled BSDF and attached textures to it?

**Comment by MothAngel** [comment]
Yes, that's what I did. I've since learned that .VRM only supports a specific type of shader, so the materials I created didn't work, it seems.

I've gotten my own project to work now via VSF SDK so I'm closing the issue, but good luck with the addon, it has great potential.
